### PR TITLE
Refactor model

### PR DESCRIPTION
**Pull request by pgrinaway**
I'm opening this PR at a very early stage so there can be more comments as I work on it. Basically, this PR aims to:
- Put the PyMC model into its own file, `model.py`
- Create a class that represents the model, instead of a dict
- Clean up any other residual bits that are not necessary

### CODE REVIEW

**Comment by jchodera** [comment]
All of these proposed changes are good ideas!

**Comment by pgrinaway** [comment]
Question: what does everyone thing is the best way to deal with the fact that in the general case, the parameter names are only known at runtime? I can of course use `setattr()` and `getattr()` to deal with that, but I don't know if that's a bit messy. Is there an alternative besides just hard-coding the variables? Or is hard-coding them a good plan?

**Comment by jchodera** [comment]
Can you give an example of which variables you are talking about?

**Comment by pgrinaway** [comment]
The parameter names, like `C_radius`, unless we want to make a new class for a model with differently-named parameters.

**Comment by pgrinaway** [comment]
I'm referring to bits like [this](https://github.com/choderalab/gbff/blob/master/parameterize-using-database.py#L49-L58) in the original code, in which stochastics only get their names at runtime, as opposed to hard-coding them as members of a class.

**Comment by kyleabeauchamp** [comment]
I see three options:
1.  Use getattr programmatically to add variables to the object
2.  Continue to use a list or dict of variables and append to them programmatically with member functions
3.  Lump together all variables of a single "type" into "vector" random variables, in which case only the length of the variables would be set at run time.  E.g the `n_molecules` and `n_gb_functionals`

I personally don't see a huge problem with hard-coding a couple of classes that each represent a "style" of GB model, as having those classes could be useful for documentation pruposes.

**Comment by kyleabeauchamp** [comment]
E.g. I imagine that we would create a class `GBNeck` that describes all of the model parameters associated with that class of GB model and the reasonable priors for said parameters.

**Comment by bas-rustenburg** [comment]
So, actually, I use both setattr and the dict at the same time. Its just a shortcut really, since it refers to the same object, but I think pymc might actually look for the attributes when calling something like 

`pymc.MAP(model)`, where  `model` is your class.

But I'm not 100% sure if thats true.

The way I define priors for my pymc models:

``` python
if "DeltaH_titrand" not in self.priors:
    self.priors["DeltaH_titrand"] = BindingModel._uniform_prior(*args)
```

And at the end of my `__init__`I do

``` python
# Add the priors as class attributes
for name, prior in self.priors.items():
    setattr(self, name, prior)
```

The reason I also use the `dict` is because I get a list of my parameter names with it, which is easy for book keeping.

**Comment by jchodera** [comment]
There are a bunch of ways to do this.

In the end, I think `pymc` scours the list of attributes of whatever object you specify for objects it knows about, so it doesn't matter what you feed it.  It's just a matter of what is most convenient.

A simple way to handle this might be to continue to use a `dict` to contain all the stochastics to be fed to `pymc`, but have this `dict` be constructed by class methods.  That way, you can break up the code in an object-oriented way, the object can have multiple fields that can cache both `pymc` objects and other objects in a sensible way, and the object can still have a `getModel()` method or `model` attribute that gives you all of the actual `pymc` objects compiled into a `dict`.

Bas's approach also works, and then the object itself is the model you feed to `pymc`, but it does litter the namespace of the object a bit.

**Comment by pgrinaway** [comment]
A couple updates:
- I've decided to go with the dictionary approach after all, as you can see from the commits. It seems cleaner and easier to deal with.
- I've made a base class with as much functionality as possible, as well as child classes for each GB model group (for instance, HCT, OBC1, OBC2 can share a class)--GBn coming soon. The classes will be instantiated like:

``` python
obc1model = model.GBFFThreeParameterModel(database, parameters,
utils.compute_hydration_energy, gbmodel=2)
```

(better names for that class are obviously welcome)
- I am using the serial version as before, but with a pre-generated `System` object, hopefully allowing us to use `CPU` without incurring much compiling overhead and getting a decent performance boost.
- I will introduce more parallel constructs if necessary in a future PR--it seems important to get this cleaned up first.

There's still a bit more to do here, but any comments are welcome.

**Comment by jchodera** [comment]
This seems pretty good for now!  

We can further discuss how to architect a more general framework in the future...

I agree with punting further improvements (e.g. parallelization) to a future PR.

**Comment by pgrinaway** [comment]
Ok, looks like the models are now working--I've adjusted the prior on GBn models to remain within the range suggested on the openmm issue tracker. In order to test the GBn models, though, I do need to get the parameters. I'll go looking now (I assume they are in the Amber parameter files), unless someone else has a better idea. Otherwise, the only thing remaining here is to combine the models and sample between them.

**Comment by jchodera** [comment]
>  In order to test the GBn models, though, I do need to get the parameters.  

Do you mean you need the current sets of parameters in use by AMBER?

They are actually set by LEaP in this ridiculous piece of code:
https://github.com/choderalab/ambermini/blob/master/leap/src/leap/unitio.c#L6031-L6259

It's possible @swails has created a much simpler Python scheme in ParmEd to assign parameters.

**Comment by jchodera** [comment]
Ah!  Here is what you want:
https://github.com/swails/ParmEd/blob/master/ParmedTools/changeradii.py

**Comment by pgrinaway** [comment]
Perfect! Thanks!

**Comment by jchodera** [comment]
These other links may be helpful:

Current AMBER protein forcefield GB conversion script:
https://simtk.org/websvn/wsvn/pyopenmm/trunk/scripts/appscripts/makeAmberGB.py

gaff2xml:
https://github.com/choderalab/gaff2xml

@swails ParmEd code for assigning GB parameters:
https://github.com/swails/ParmEd/blob/master/ParmedTools/changeradii.py

LEaP code that handles parameter assignment:
https://github.com/choderalab/ambermini/blob/master/leap/src/leap/unitio.c#L6050-L6204

References for AMBER GB models:
One is attached.  I don't have access to the others:
http://onlinelibrary.wiley.com/doi/10.1002/jcc.10126/abstract
http://onlinelibrary.wiley.com/doi/10.1002/1097-0282(2000)56:4%3C275::AID-BIP10024%3E3.0.CO;2-E/abstract

**Comment by pgrinaway** [comment]
Update:
- I took the GBn radii from unitio.c, but there didn't appear to be any screening factors in there for igb=7, so I took the screening factor parameters from [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L554-L633).
- An empirical investigation yielded that the maximum radius that can be given to the GBn force is somewhere around 1.91113A. I think the range is supposed to be [1.0, 2.0], so I'm not sure if I should report this as a bug. For now, the prior has been changed to remain within that range.

**Comment by jchodera** [comment]
Please report this bug!

**Comment by pgrinaway** [comment]
Reported. Now working on adding in the GBn2 parameters. The GBn model is sampling, aside from the odd range issue.

**Comment by jchodera** [comment]
GBn2 has some additional parameters, right?  What prior are you using for these guys?

**Comment by jchodera** [comment]
Also, maybe it's worth merging this and tackling GBn2 in a separate PR?

**Comment by swails** [comment]
> I took the GBn radii from unitio.c, but there didn't appear to be any screening factors in there for igb=7, so I took the screening factor parameters from here.

Those are from the sander source code, FYI.  ParmEd has them, too.

**Comment by pgrinaway** [comment]
@jchodera : 

> GBn2 has some additional parameters, right? What prior are you using for these guys?

I'm using very broad normals (`tau=0.0001`), since the support of these parameters seems to be all reals. Correct me if I'm wrong on that, though.

> Also, maybe it's worth merging this and tackling GBn2 in a separate PR?

fair enough, let me undo whatever I did to break automatic merging, then we can take one more pass and merge.

@swails : Thanks!

**Comment by pgrinaway** [comment]
Ok, I think this is essentially ready to merge.

**Comment by jchodera** [comment]
Go for it!

**Pull request merged**
