### PR TITLE
Updating rebuild_freesolv to use openmoltools and create output directories if not present

### PR DESCRIPTION
**Pull request by davidlmobley**
Replacing gaff2xml with openmoltools; create output directories if not already present.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Looks good to me

**Comment by jchodera** [comment]
Awesome!  Thanks, guys!

**Comment by davidlmobley** [comment]
For the record, I have my student getting going to take off from this point
and generate GROMACS inputs so we can re-run everything. It will probably
take him a bit of time as he has to figure out how to use GitHub,
incorporate some stuff into a 'gromacs' module we'll add to openmoltools,
etc. Once this is done and tested/working presumably we can move this
functionality from here to FreeSolv, where it would make more sense.

On Fri, May 1, 2015 at 3:16 PM, John Chodera notifications@github.com
wrote:

> Awesome! Thanks, guys!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choderalab/gbff/pull/15#issuecomment-98253289.

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
> For the record, I have my student getting going to take off from this point and generate GROMACS inputs so we can re-run everything.

What path are you thinking for this?

I really think we want to go from `Tripos mol2` -> `gaff mol2` -> `Amber prmtop/inpcrd` -> `gromacs via ACPYPE` for this for now.  Eventually, we can switch to `ParmEd` to do all of this, but this seems like the most robust workflow for now.

**Comment by davidlmobley** [comment]
Yes, that's exactly the plan.

This is _also_ what I'm planning for our binary mixture or arbitrary solute
A in arbitrary solvent B simulations, though it will require a slightly
different workflow since water can't in general be treated as an arbitrary
solute/solvent. Also, I may need to tweak things on the GROMACS end as if I
set up the mixture of N molecules of A plus M of B and convert via ACPYPE,
I tend to get huge GROMACS topology files since each topology contains
parameters for N molecules of A plus M of B (which is rather redundant). It
will work but seems inelegant.

On Fri, May 1, 2015 at 3:33 PM, John Chodera notifications@github.com
wrote:

> For the record, I have my student getting going to take off from this
> point and generate GROMACS inputs so we can re-run everything.
> 
> What path are you thinking for this?
> 
> I really think we want to go from Tripos mol2 -> gaff mol2 -> Amber
> prmtop/inpcrd -> gromacs via ACPYPE for this for now. Eventually, we can
> switch to ParmEd to do all of this, but this seems like the most robust
> workflow for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choderalab/gbff/pull/15#issuecomment-98255843.

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Er, just to clarify though - you listed Tripos mol2 as your starting point,
whereas the current tool starts with SMILES. I thought we'd agreed SMILES
was the primary data/starting point, so it would be SMILES -> Tripos mol2
-> ...

On Fri, May 1, 2015 at 3:33 PM, John Chodera notifications@github.com
wrote:

> For the record, I have my student getting going to take off from this
> point and generate GROMACS inputs so we can re-run everything.
> 
> What path are you thinking for this?
> 
> I really think we want to go from Tripos mol2 -> gaff mol2 -> Amber
> prmtop/inpcrd -> gromacs via ACPYPE for this for now. Eventually, we can
> switch to ParmEd to do all of this, but this seems like the most robust
> workflow for now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choderalab/gbff/pull/15#issuecomment-98255843.

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
> Er, just to clarify though - you listed Tripos mol2 as your starting point, whereas the current tool starts with SMILES. I thought we'd agreed SMILES was the primary data/starting point, so it would be SMILES -> Tripos mol2 -> ...

Yes, you are 100% correct!  I accidentally omitted that step!

**Pull request merged**
