### PR TITLE
[WIP] Initial cleanup of repo and code

### PR DESCRIPTION
**Pull request by pgrinaway**
Added current version of code, with modifications to sample different GB models. Still a bit of debugging to do. (Apologies about all the files--perhaps we can discuss which of these are necessary to have in the repo)

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Can we just delete the freesolve repo from the current one?  Otherwise this repo will get out of control.

**Comment by pgrinaway** [comment]
I'm +1 on this idea.

**Comment by pgrinaway** [comment]
Ok, since the version control, etc. is done in another repo, I'm going to remove these files from this repo. We can add them back if necessary.

**Comment by kyleabeauchamp** [comment]
Maybe squash these into a single commit to avoid having a history with the 6K files?

**Comment by pgrinaway** [comment]
Ok, going to close this and reopen with fewer commits

**Comment by jchodera** [comment]
Sorry about this guys---the pressing deadline of a talk and issues with getting FreeSolv improvements checked in meant it was easier for me to pull in a copy into the `gbff` repo for a short time.

How about this solution:
- Start a clean repo with no FreeSolv set inside (or remove it completely somehow)
- Have the `gbff` setup scripts check out a copy of the FreeSolv repo
- We probably don't even need to have our own AM1-BCC parameterization step anymore since we have parameterized [GAFF/AM1-BCC mol2 files in FreeSolv](https://github.com/choderalab/FreeSolv/tree/master/mol2files_gaff), though we may need to update those to new "canonical" AM1-BCC

**Comment by kyleabeauchamp** [comment]
Sounds good to me.

**Comment by pgrinaway** [comment]
+1 for me as well.

**Pull request closed without merging**
