### PR TITLE
Changes for parallelization, instructions

### PR DESCRIPTION
**Pull request by pgrinaway**
This PR contains the latest changes to the GBFF repo. It also contains instructions on running the script.

### CODE REVIEW

**Comment by pgrinaway** [comment]
The outputs that I generated before are too large to upload, but they are on the cluster.

**Comment by jchodera** [comment]
Thanks!  As long as the path to the data is in the README, we're good!  Merge when ready.

**Comment by jchodera** [comment]
For "get Freesolv database" in the README, can you elaborate a bit on which version you grabbed and via what route you pulled it?

**Comment by pgrinaway** [comment]
Ok, I've added a commit id as well as the git instruction to fetch the database for the FreeSolv that I used. Is it ok to put the cluster path on here?

**Comment by jchodera** [comment]
Yes, thanks!

**Comment by pgrinaway** [comment]
Ok, can I merge this then?

**Comment by pgrinaway** [comment]
Ok, done!

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
